require File.expand_path('../core/hash', __FILE__)
require File.expand_path('../core/object/io_command_processor', __FILE__)
require File.expand_path('../core/object/pty_command_processor', __FILE__)
require File.expand_path('../core/object', __FILE__)
require File.expand_path('../core/string', __FILE__)
