require File.expand_path('../wait', __FILE__)
require File.expand_path('../services/simple_log', __FILE__)
require File.expand_path('../services/local_server', __FILE__)
require File.expand_path('../services/rails_server', __FILE__)
require File.expand_path('../services/oauth_stub_server', __FILE__)
require File.expand_path('../services/oauth_stub_configurer', __FILE__)
require File.expand_path('../services/no_op_service', __FILE__)
