require File.expand_path('../wait', __FILE__)
require File.expand_path('../pages/base', __FILE__)
require File.expand_path('../pages/accountright_live_login', __FILE__)
require File.expand_path('../pages/customer_files', __FILE__)
require File.expand_path('../dsl', __FILE__)
