require File.expand_path('../pages/base', __FILE__)
require File.expand_path('../pages/live_login', __FILE__)
require File.expand_path('../pages/customer_files', __FILE__)
require File.expand_path('../pages/fragments/contact_overview', __FILE__)
require File.expand_path('../pages/fragments/contact_detail', __FILE__)
require File.expand_path('../pages/contacts', __FILE__)
require File.expand_path('../pages/contact_details', __FILE__)
