api:
  key: apikeyabcdefghijklmnopqr
  uri: http://localhost:3003
live_login:
  base_uri: http://localhost:3002
  path: /oauth2/v1/authorize
  client_id: clientidabcdefghijkmnopq
  client_secret: clientsecretabcdefghijkl
test:
  timeout_in_seconds: 3
  app_uri: http://localhost:3001
  live_user:
    username: arl_user@myob.com
    password: arl_password
  customer_file:
    Id: 123aaaaa-bb98-21cc-dd89-eeeeeeeeeee1
    Name: Clearwater Pty Ltd
  customer_file_user:
    username: cf_user
    password: cf_password
