api:
  key: test_key
  uri: http://localhost:3003
live_login:
  base_uri: http://localhost:3002
  client_id: test_client_id
  client_secret: test_client_secret
  grant_type: password
  path: /oauth2/v1/authorize
  scope: CustomerFile
acceptance:
  app_uri: http://localhost:3001
  live_user:
    username: arl_user
    password: arl_password
  customer_file: Clearwater Pty Ltd
